apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-logs-api
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: plane
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z plane-db 5432; do sleep 2; done
              until nc -z plane-redis 6379; do sleep 2; done
              until nc -z plane-mq 5672; do sleep 2; done
              sleep 5
      containers:
        - name: api
          image: artifacts.plane.so/makeplane/plane-backend:v1.0.0
          command: ["./bin/docker-entrypoint-api.sh"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: plane-secrets
          volumeMounts:
            - name: logs
              mountPath: /code/plane/logs
          livenessProbe:
            exec:
              command:
                - echo
                - "hey whats up"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 15
          readinessProbe:
            exec:
              command:
                - echo
                - "hey whats up"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: plane-logs-api
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: plane
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
