apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-logs-beat-worker
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat-worker
  namespace: plane
  labels:
    app: beat-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat-worker
  template:
    metadata:
      labels:
        app: beat-worker
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z api 8000; do sleep 2; done
              sleep 5
      containers:
        - name: beat-worker
          image: artifacts.plane.so/makeplane/plane-backend:v1.0.0
          command: ["./bin/docker-entrypoint-beat.sh"]
          envFrom:
            - secretRef:
                name: plane-secrets
          volumeMounts:
            - name: logs
              mountPath: /code/plane/logs
          livenessProbe:
            exec:
              command:
                - echo
                - "hey whats up"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 15
          readinessProbe:
            exec:
              command:
                - echo
                - "hey whats up"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: plane-logs-beat-worker
