apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-logs-migrator
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  namespace: plane
  labels:
    app: migrator
spec:
  template:
    metadata:
      labels:
        app: migrator
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z plane-db 5432; do sleep 2; done
              until nc -z plane-redis 6379; do sleep 2; done
              sleep 5
      containers:
        - name: migrator
          image: artifacts.plane.so/makeplane/plane-backend:v1.0.0
          command: ["./bin/docker-entrypoint-migrator.sh"]
          envFrom:
            - secretRef:
                name: plane-secrets
          volumeMounts:
            - name: logs
              mountPath: /code/plane/logs
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: plane-logs-migrator
  backoffLimit: 4
