apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-pgdata
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-db
  namespace: plane
  labels:
    app: plane-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plane-db
  template:
    metadata:
      labels:
        app: plane-db
    spec:
      containers:
        - name: postgres
          image: postgres:15.7-alpine
          args: ["-c", "max_connections=1000"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: plane-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plane-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "plane"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d plane
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 20
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d plane
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: plane-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: plane-db
  namespace: plane
spec:
  selector:
    app: plane-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
