apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: plane
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      initContainers:
        - name: wait-for-services
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z web 3000; do sleep 2; done
              until nc -z api 8000; do sleep 2; done
              until nc -z space 3000; do sleep 2; done
              until nc -z admin 3000; do sleep 2; done
              until nc -z live 3000; do sleep 2; done
              sleep 3
      containers:
        - name: proxy
          image: artifacts.plane.so/makeplane/plane-proxy:v1.0.0
          ports:
            - containerPort: 80
          env:
            - name: SERVICE_URL_PLANE
              value: "http://localhost"
            - name: APP_DOMAIN
              value: ""
            - name: SITE_ADDRESS
              value: ":80"
            - name: FILE_SIZE_LIMIT
              value: "5242880"
            - name: BUCKET_NAME
              value: "uploads"
          livenessProbe:
            exec:
              command:
                - curl
                - "-f"
                - http://127.0.0.1:80
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 10
            failureThreshold: 15
          readinessProbe:
            exec:
              command:
                - curl
                - "-f"
                - http://127.0.0.1:80
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 10
            failureThreshold: 15
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: plane
spec:
  selector:
    app: proxy
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
