apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-redisdata
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-redis
  namespace: plane
  labels:
    app: plane-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plane-redis
  template:
    metadata:
      labels:
        app: plane-redis
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:7.2.5-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redisdata
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 20
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: plane-redisdata
---
apiVersion: v1
kind: Service
metadata:
  name: plane-redis
  namespace: plane
spec:
  selector:
    app: plane-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
