apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: rocketchat
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: docker.io/bitnami/mongodb:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_REPLICA_SET_MODE
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_REPLICA_SET_MODE
            - name: MONGODB_REPLICA_SET_NAME
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_REPLICA_SET_NAME
            - name: MONGODB_PORT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_PORT_NUMBER
            - name: MONGODB_INITIAL_PRIMARY_HOST
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_INITIAL_PRIMARY_HOST
            - name: MONGODB_INITIAL_PRIMARY_PORT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_INITIAL_PRIMARY_PORT_NUMBER
            - name: MONGODB_ADVERTISED_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_ADVERTISED_HOSTNAME
            - name: MONGODB_ENABLE_JOURNAL
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: MONGODB_ENABLE_JOURNAL
            - name: ALLOW_EMPTY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rocketchat-secrets
                  key: ALLOW_EMPTY_PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /bitnami/mongodb
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: rocketchat
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
